name: Feature request
description: Suggest an improvement
title: '[Feature]: '
labels: ['enhancement']
body:
    - type: textarea
      id: problem
      attributes:
          label: Problem statement
          description: What limitation are you trying to solve
      validations:
          required: true
    - type: textarea
      id: proposal
      attributes:
          label: Proposed solution
          description: Preferred API or behavior
      validations:
          required: true
    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives considered
      validations:
          required: false
